apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashboard-external-auth
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.org/ssl-services: kubernetes-dashboard
spec:
  rules:
  - host: k8s-secret-dashboard.apps.192.168.18.24.nip.io
    http: 
      paths:
        - backend:
            service: 
              name: kubernetes-dashboard
              port:
                number: 443
          path: /
          pathType: Prefix
